services:
  redis:
    image: docker-hub.dahuatech.com/redis:6-alpine
    restart: always
    environment:
      REDISCLI_AUTH: dahua123
    volumes:
      - ./volumes/redis/data:/data
    command: redis-server --requirepass dahua123
    ports:
      - "12061:6379"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "redis-cli -a dahua123 ping | grep -q PONG",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 10s

  server:
    image: harbor-itdm.dahuatech.com/llms/domestic-analysis-report:uat-2.0.0-0114
    command: uvicorn app:app --host 0.0.0.0 --port 80
    environment:
      - APP_ENVIRONMENT=uat
      - APP_MODEL=gpt-oss
      - APP_LOG_LEVEL=info
      - APP_MODEL_CONCURRENT=8
      - MAX_SYSTEM_CONCURRENT=2
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=dahua123
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 30s
    healthcheck:
      test: "curl --fail --request GET 'localhost:80' || exit 1"
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s

  celery-worker:
    image: harbor-itdm.dahuatech.com/llms/domestic-analysis-report:uat-2.0.0-0114
    command: celery -A src.config.celery_config worker --loglevel=info
    environment:
      - APP_ENVIRONMENT=uat
      - APP_MODEL=gpt-oss
      - APP_LOG_LEVEL=info
      - APP_MODEL_CONCURRENT=8
      - MAX_SYSTEM_CONCURRENT=2
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=dahua123
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 30s
    healthcheck:
      test: "celery -A src.config.celery_config inspect ping || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - /home/codewen_workspace/domestic_analysis_report/fix_datas/fix_data.json:/app/tests/fix_data.json

  celery-flower:
    image: harbor-itdm.dahuatech.com/llms/domestic-analysis-report:uat-2.0.0-0114
    command: celery -A src.config.celery_config flower --port=7777
    environment:
      - APP_ENVIRONMENT=uat
      - APP_MODEL=gpt-oss
      - APP_LOG_LEVEL=info
      - APP_MODEL_CONCURRENT=8
      - MAX_SYSTEM_CONCURRENT=2
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=dahua123
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "12062:7777"
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: any
        delay: 30s
    healthcheck:
      test: "celery -A src.config.celery_config inspect ping || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  proxy:
    image: harbor-itdm.dahuatech.com/base/nginx:1.22-alpine
    ports:
      - target: 80
        published: 12060
        mode: host
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
    command: |
      /bin/sh -c "echo '
      user nobody;
      worker_processes auto;
      events {
        worker_connections 1024;
      }
      http {
        client_max_body_size 500m;
        resolver 127.0.0.11 valid=30s; # Docker 内置 DNS
        server {
          listen 80;
          location / {
            set $$target_service http://server:80; 
            proxy_pass $$target_service;
            proxy_set_header Host $$http_host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_set_header Connection \"\";
            proxy_connect_timeout 600s;
            proxy_send_timeout 600s;
            proxy_read_timeout 600s;
          }
        }
      }' > /etc/nginx/nginx.conf && nginx -t && nginx -g 'daemon off;'"